### PR TITLE
(Issue #14) Install - SQL Build Versions Corrected

### PR DESCRIPTION
**Pull request by AnonDevelopment**
Pull request for issue #14 
Install sql build version fix

### CODE REVIEW

**Comment by WillStrohl** [comment]
We're going to need a minor modification made to your PR.  We want to only support version 2012 and higher, but 2008 would be validated with your PR.  Can you please make that update first?

**Comment by AnonDevelopment** [comment]
Are you sure? isValidVersion is set to false on line 480. Anyways I went ahead and set each case.

Case 10 for SQL Server 2008 has been explicitly set to false. Submitting another PR.

**Comment by AnonDevelopment** [comment]
that's what i get for not paying attention, shared value...

**Comment by WillStrohl** [comment]
Thanks for your work on this.  Unfortunately for you, we changed how we're distributing the Hotcakes Commerce CMS.  It's now going to be purely a distribution model, so this issue and its related pull request are going to be closed.  I'm sorry that we can't accept the pull request.

**Pull request closed without merging**
